In [1]:
import pandas as pd
import tensorflow as tf

In [29]:
iris_data = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')
print(iris_data.columns)
iris_data.head(3)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa

In [30]:
iris = pd.get_dummies(iris_data)   # onehot-encoding : 범주형 데이터를 0, 1로 바꿔주는 것
iris.tail(3)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

In [25]:
x_data = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y_data = iris[['품종_setosa',	'품종_versicolor',	'품종_virginica']]
print(x_data.shape, y_data.shape)

(150, 4) (150, 3)


In [26]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)   # softmax : 확률로 예측하기 위해 사용(0~100%)
                                                        # activation : 활성화 함수
                                                        # softmax와 sigmoid의 차이는 무엇인가
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',          # 분류에 사용하는 loss는 'crossentropy', 회귀는 'mse'
              metrics='accuracy')

In [31]:
model.fit(x_data, y_data, epochs=100)

Epoch 1/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1576 - accuracy: 0.9800
Epoch 2/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1569 - accuracy: 0.9800
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1570 - accuracy: 0.9800
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1569 - accuracy: 0.9800
Epoch 5/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1566 - accuracy: 0.9800
Epoch 6/100
5/5 [==============================] - 0s 1ms/step - loss: 0.1566 - accuracy: 0.9800
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1570 - accuracy: 0.9800
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1568 - accuracy: 0.9800
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1565 - accuracy: 0.9800
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.1561 - accuracy: 0.9800
Epoch 11/100
5/5 [===========

In [34]:
print('Predictions: ', model.predict(x_data[0:5]))

Predictions:  [[9.9944872e-01 5.5129593e-04 2.1971235e-08]
 [9.9713504e-01 2.8647599e-03 2.3712121e-07]
 [9.9889463e-01 1.1053133e-03 8.3199495e-08]
 [9.9701798e-01 2.9817349e-03 4.1189867e-07]
 [9.9959677e-01 4.0325374e-04 1.6845533e-08]]


In [36]:
model.get_weights()    # 학습 가중치

[array([[ 0.39230064,  0.26941308, -1.1107999 ],
        [ 3.4518332 ,  0.20041619, -0.70923555],
        [-3.2122998 ,  0.07182769,  1.9626979 ],
        [-4.185777  , -1.1870713 ,  1.9392874 ]], dtype=float32),
 array([ 2.0943658,  1.4008449, -1.7790705], dtype=float32)]