In [3]:
import pandas as pd
import tensorflow as tf

In [4]:
iris_data = pd.read_csv('https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv')
iris_data.head(3)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa

In [5]:
iris = pd.get_dummies(iris_data)   # onehot-encoding : 범주형 데이터를 0, 1로 바꿔주는 것
iris.tail(3)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

In [6]:
x_data = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y_data = iris[['품종_setosa',	'품종_versicolor',	'품종_virginica']]
print(x_data.shape, y_data.shape)

(150, 4) (150, 3)


In [7]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)   # softmax : 확률로 예측하기 위해 사용(0~100%)
                                                        # activation : 활성화 함수
                                                        # softmax와 sigmoid의 차이는 무엇인가
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',          # 분류에 사용하는 loss는 'crossentropy', 회귀는 'mse'
              metrics='accuracy')

In [10]:
model.fit(x_data, y_data, epochs=1000, verbose=0)
model.fit(x_data, y_data, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0445 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0480 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 4ms/step - loss: 0.0480 - accuracy: 0.9867
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0475 - accuracy: 0.9867
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0475 - accuracy: 0.9733
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0457 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0581 - accuracy: 0.9733
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0417 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0430 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0478 - accuracy: 0.9800


In [15]:
print(model.predict(x_data[0:5]))   # 예측값
print(y_data[0:5])                  # 실제값

[[1.0000000e+00 8.0838120e-10 5.4477001e-09]
 [1.0000000e+00 1.5960152e-08 3.6346812e-08]
 [1.0000000e+00 5.6316281e-09 2.6509500e-08]
 [1.0000000e+00 5.8512657e-09 1.4684459e-08]
 [1.0000000e+00 4.2403084e-10 3.5962278e-09]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [18]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.get_weights()    # 학습 가중치