In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
iris_data = pd.read_csv('https://raw.githubusercontent.com/hwaneGithub/hwaneGithub.github.io/master/Database/iris.csv')
print(iris_data.columns)
iris_data.head(3)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa

In [3]:
iris = pd.get_dummies(iris_data)   # onehot-encoding : 범주형 데이터를 0, 1로 바꿔주는 것
iris.tail(3)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

In [4]:
x_data = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y_data = iris[['품종_setosa',	'품종_versicolor',	'품종_virginica']]
print(x_data.shape, y_data.shape)

(150, 4) (150, 3)


In [5]:
X = tf.keras.layers.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation='softmax')(X)   # softmax : 확률로 예측하기 위해 사용(0~100%)
                                                        # activation : 활성화 함수
                                                        # softmax와 sigmoid의 차이는 무엇인가
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',          # 분류에 사용하는 loss는 'crossentropy', 회귀는 'mse'
              metrics='accuracy')

In [11]:
model.fit(x_data, y_data, epochs=1000, verbose=0)
model.fit(x_data, y_data, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0952 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0953 - accuracy: 0.9667
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0951 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0948 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0949 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0948 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0952 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0952 - accuracy: 0.9800
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0949 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0946 - accuracy: 0.9800


In [12]:
print('Predictions: ', model.predict(x_data[0:5]))

Predictions:  [[9.9998415e-01 1.5912899e-05 2.1745136e-12]
 [9.9986482e-01 1.3513572e-04 7.8687785e-11]
 [9.9995399e-01 4.6004523e-05 1.7479088e-11]
 [9.9980026e-01 1.9974551e-04 1.6867724e-10]
 [9.9998808e-01 1.1870219e-05 1.4589613e-12]]


In [13]:
model.get_weights()    # 학습 가중치

[array([[ 1.0385598 ,  0.07603838, -1.2376877 ],
        [ 5.2611265 ,  1.3675951 , -1.0059806 ],
        [-5.514683  , -0.6004318 ,  1.549314  ],
        [-7.520213  , -1.820285  ,  3.8955703 ]], dtype=float32),
 array([ 2.957803 ,  2.42572  , -2.5254128], dtype=float32)]