In [1]:
import pandas as pd
import tensorflow as tf

In [2]:
iris_data = pd.read_csv('https://raw.githubusercontent.com/hwaneGithub/hwaneGithub.github.io/master/Database/iris.csv')
iris_data.head(3)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa

In [3]:
iris = pd.get_dummies(iris_data)   # onehot-encoding : 범주형 데이터를 0, 1로 바꿔주는 것
iris.tail(3)

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
147   6.5  3.0    5.2   2.0          0              0             1
148   6.2  3.4    5.4   2.3          0              0             1
149   5.9  3.0    5.1   1.8          0              0             1

In [4]:
x_data = iris[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
y_data = iris[['품종_setosa',	'품종_versicolor',	'품종_virginica']]
print(x_data.shape, y_data.shape)

(150, 4) (150, 3)


In [5]:
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation='swish')(X)
H = tf.keras.layers.Dense(8, activation='swish')(H)
H = tf.keras.layers.Dense(8, activation='swish')(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)   # softmax : 확률로 예측하기 위해 사용(0~100%)
                                                        # activation : 활성화 함수
                                                        # softmax와 sigmoid의 차이는 무엇인가
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',          # 분류에 사용하는 loss는 'crossentropy', 회귀는 'mse'
              metrics='accuracy')

In [6]:
model.fit(x_data, y_data, epochs=1000, verbose=0)
model.fit(x_data, y_data, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0476 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0446 - accuracy: 0.9867
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0477 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0471 - accuracy: 0.9733
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0460 - accuracy: 0.9867
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0418 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0499 - accuracy: 0.9867
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0445 - accuracy: 0.9933
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0429 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0421 - accuracy: 0.9800


In [7]:
print(model.predict(x_data[0:5]))   # 예측값
print(y_data[0:5])                  # 실제값

[[9.9999976e-01 1.8471884e-07 1.1136127e-21]
 [9.9999797e-01 1.9990737e-06 2.0075490e-19]
 [9.9999881e-01 1.2021609e-06 9.1187344e-20]
 [9.9999630e-01 3.7503737e-06 1.4508160e-18]
 [9.9999988e-01 1.6280889e-07 1.0412413e-21]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0


In [8]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense (Dense)                (None, 8)                 40        
_________________________________________________________________
dense_1 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.get_weights()    # 학습 가중치

[array([[ 0.5430115 , -0.31391189, -0.31312084, -0.37174067,  0.20550248,
          0.38390815,  0.09994462,  0.15238202],
        [ 0.5598392 ,  0.23797907,  0.2314186 ,  0.18711305, -0.2337382 ,
          0.31142378, -0.00664031, -0.9480124 ],
        [-0.6825475 , -0.04031748, -0.3720951 , -0.35805258,  0.26807618,
         -0.38030073, -0.6006502 ,  0.05975436],
        [-0.35838133, -0.60064644,  0.2427681 ,  0.34610558,  0.6362    ,
         -0.751285  , -0.13196746,  0.5222647 ]], dtype=float32),
 array([ 0.4141106 ,  0.17635614,  0.4161548 ,  0.26771495, -0.04738381,
         0.47636747,  0.23181738, -0.04287931], dtype=float32),
 array([[ 4.78535891e-01,  1.38116443e+00, -5.69686651e-01,
         -4.56030816e-01, -6.11006379e-01,  4.83280271e-01,
          4.18393821e-01, -7.38533854e-01],
        [-9.62090075e-01, -6.56890452e-01,  8.49770904e-02,
         -5.25316358e-01,  5.86384892e-01, -1.16221141e-03,
         -4.82909799e-01,  5.28607786e-01],
        [-1.23817551e+00, 